version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "81:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./app/public:/app/public
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app/